version: '3.8'

services:
  postgres:
    image: postgres:18.3-alpine
    container_name: postgres-trevo-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  redis:
    image: redis:8.4-alpine
    container_name: redis-trevoo-db
    environment:
      REDIS_ARGS: >
              --requirepass ${REDIS_PASSWORD}
              --appendonly yes
              --io-threads 4
              --io-threads-do-reads yes
              --search-io-threads 4  # I/O threads для поисковых запросов
              --search-oom IGNORE
    ports:
      - "6379:6379"  # Redis порт
      - "8001:8001"  # Redis Insight (веб-интерфейс)
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # порт для S3 API
      - "9001:9001"   # порт для веб-консоли
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}      # логин администратора
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}  # пароль администратора (минимум 8 символов)

    volumes:
      - ${MINIO_PATH_FOLDER}:/data                    # монтируем локальную папку для хранения данных
    command: server /data --console-address ":9001"
    restart: unless-stopped